version: "3"
services:
  app:
    image: ghcr.io/mikecao/umami:postgresql-latest
    container_name: umami
    #restart: always
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://umami:${POSTGRES_PASSWORD}@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: ${HASH_SALT}
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    container_name: umami_db
    #restart: always
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - ${UMAMI_DB_DIR}:/var/lib/postgresql/data
